<!-- Main content -->
			<div class="content-wrapper">

				
                <!-- Grid -->
				<div class="row">
					<div class="col-md-6">

						<!-- Horizontal form -->
						<div class="panel panel-flat">
							<div class="panel-heading">
								<h5 class="panel-title">Profil</h5>
								<div class="heading-elements">
									<ul class="icons-list">
				                		<li><a data-action="collapse"></a></li>
				                		
				                	</ul>
			                	</div>
		                	</div>

							<div class="panel-body">
								<form class="form-horizontal" action="/users/savechanges" method="post">
									<input type="hidden" name="user_id" value="<?php echo $this->user[0]['user_id']; ?>">
									<div class="form-group">
									
										<label class="control-label col-lg-2">Name</label>
										<div class="col-lg-10">
											<input type="text" name="username" class="form-control" value="<?php echo $this->user[0]['username']; ?>">
										</div>
									</div>
									
									<div class="form-group">
										<label class="control-label col-lg-2">E-Mail</label>
										<div class="col-lg-10">
											<input type="text" name="email" class="form-control" readonly="readonly" value="<?php echo $this->user[0]['email']; ?>">
										</div>
									</div>
									
									<div class="form-group">
										<label class="control-label col-lg-2">Password</label>
										<div class="col-lg-10">
											<input type="password" name="password" class="form-control">
										</div>
									</div>
									
									<div class="form-group">
										<label class="control-label col-lg-2">Password wiederholen</label>
										<div class="col-lg-10">
											<input type="password" name="password2" class="form-control">
										</div>
									</div>

			                        <div class="form-group">
										<label class="control-label col-lg-2">Rolle</label>
										<div class="col-lg-10" style="padding-top:10px;">
										<select class="selectbox">
											<option value="admin" <?php if($this->user[0]['role_id'] == 'admin'){echo 'selected';}?>>Administrator</option>
											<option value="mod" <?php if($this->user[0]['role_id'] == 'mod'){echo 'selected';}?>>Mitarbeiter</option>
											<option value="guest" <?php if($this->user[0]['role_id'] == 'guest'){echo 'selected';}?>>Gast</option>
										</select>
										</div>
									</div>
									

									<div class="text-right">
										<button type="submit" class="btn btn-primary">Speichern <i class="icon-arrow-right14 position-right"></i></button>
									</div>
								</form>
							</div>
						</div>
						<!-- /horizotal form -->

					</div>

					
				</div>
				<!-- /grid -->

			</div>
			<!-- /main content -->