<!-- Main content -->

			<div class="content-wrapper">

				
               <!-- Basic datatable -->
					<div class="panel panel-flat">
						<div class="panel-heading">
							<h5 class="panel-title">Benutzer</h5>
							<div class="heading-elements">
								<ul class="icons-list">
			                		<li><a data-action="collapse"></a></li>
			                	</ul>
		                	</div>
						</div>

						

						<table class="table datatable-html">
							<thead>
								<tr>
									<th>Name</th>
									<th>E-Mail</th>
									<th>Rolle</th>
									<th class="text-center">Actions</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->users as $users){ ?>
								<tr>
									<td><?php echo $users['username']; ?></td>
									<td><?php echo $users['email']; ?></td>
									<td><?php echo $users['role_id']; ?></td>
									<td class="text-center">
										<ul class="icons-list">
											<li class="dropdown">
												<a href="#" class="dropdown-toggle" data-toggle="dropdown">
													<i class="icon-menu9"></i>
												</a>

												<ul class="dropdown-menu dropdown-menu-right">
													<li><a href="/users/change?user=<?php echo $users['user_id']; ?>"><i class="icon-pencil3"></i> Ändern</a></li>
													<li><a href="#" data-toggle="modal" data-target="#modal_default-<?php echo $users['user_id']; ?>"><i class="icon-trash"></i> Löschen</a></li>
												</ul>
											</li>
										</ul>
									</td>
								</tr>
								
								
					
								<?php } ?>																
							</tbody>
						</table>
					</div>
					<!-- /basic datatable -->

			</div>
			<!-- /main content -->
			
			<?php foreach($this->users as $users){ ?>
			<!-- Basic modal -->
					<div id="modal_default-<?php echo $users['user_id']; ?>" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal">&times;</button>
									<h5 class="modal-title">Benutzer löschen</h5>
								</div>

								<div class="modal-body">
									<hr>

									<h6 class="text-semibold"><?php echo $users['username']; ?> / <?php echo $users['email']; ?></h6>
									<p>Möchten Sie den Benutzer wirklich löschen?</p>
								</div>

								<div class="modal-footer">
									<button type="button" class="btn btn-link" data-dismiss="modal">Schließen</button>
									<a href="/users/delete?user=<?php echo $users['user_id']; ?>"><button type="button" class="btn btn-primary">Löschen</button></a>
								</div>
							</div>
						</div>
					</div>
					<!-- /basic modal -->
			
			<?php } ?>			
			