<!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

			<!-- Main content -->
			<div class="content-wrapper">

				<!-- Content area -->
				<div class="content">

					<!-- Error title -->
					<div class="text-center content-group">
						<h1 class="error-title">403</h1>
						<h5>
<?php if (\BjyAuthorize\Guard\Controller::ERROR === $error) : ?>
        Sie haben nicht die erforderlichen Rechte für den Bereich "<?php echo($controller);?>"        
        <?php if ($action) : ?>
        ::<?php echo($action);?>Action()
        <?php endif;?>
        .
    <?php elseif (\BjyAuthorize\Guard\Route::ERROR === $error)  : ?>
        Sie haben nicht die erforderlichen Rechte für den Bereich "<?php echo $route;?>".
    <?php elseif ($error == 'error-unauthorized') : ?>
        YSie haben nicht die erforderlichen Rechte: <?php echo $reason; ?>.
    <?php else : ?>
    An unknown error occurred.
    <?php endif;?>
</h5>
					</div>
					<!-- /error title -->


					<!-- Error content -->
					<div class="row">
						<div class="col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3">
								

								<div class="row">
																		<div class="col-sm-12">
										<a href="/user/login" class="btn btn-default btn-block content-group"><i class="icon-menu7 position-left"></i> Login</a>
									</div>
								</div>
							
						</div>
					</div>
					<!-- /error wrapper -->


					<!-- Footer -->
					<div class="footer text-muted text-center">
						&copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
					</div>
					<!-- /footer -->

				</div>
				<!-- /content area -->

			</div>
			<!-- /main content -->

		</div>
		<!-- /page content -->

	</div>
	<!-- /page container -->
