Lieber Tire Management Benutzer,

jemand hat das Zurücksetzen des Passworts für Ihr Tire Management Benutzerkonto angefordert:

Falls Sie das Zurücksetzen des Passworts nicht angefordert haben, ignorieren Sie einfach diese E-Mail. Es wird dann nichts weiter passieren.

Um Ihr Passwort zurückzusetzen, besuchen Sie folgende Adresse (Dieser Link ist für die nächsten 10 Minuten gültig):

<?php echo $this->serverUrl($this->url('zfcuser/resetpassword', array('userId' => $this->record->getUserId(), 'token' => $this->record->getRequestKey()))); ?>

